spring.application.name=WeRecomU


spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.model=gemini-2.5-flash


spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001